# skaffold.yaml

# nonk8s
apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: aramzakaryan/auth
      context: auth-4001
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**'
            dest: .
